### ISSUE TITLE
Segmentations availability

### ISSUE THREAD

**Issue by saugatkandel** [KosinskiLab/colabseg#8]
Hello! This is very interesting work, so congrats to the authors.

The paper mentions over 50 annotated tomograms. Are the annotations available to download?

**Comment by jkosinski** [comment]
Hi, sorry for the delay in answering. What information you mean is exactly, the binned tomograms and membrane segmentations?

**Comment by saugatkandel** [comment]
Yes, I might have missed the link if they are already available somewhere.

(Sorry for the delayed reply on my end as well.)

**Comment by rkjensen** [comment]
Hi @saugatkandel 
Thanks for you interest.
We will make all of the data/segmentations available in an upcoming publication together with also particle localisations of a number of different protein complexes, but for now you can download tomograms and segmentations from this link:
[tomgorams/segmentations](https://oc.embl.de/index.php/s/9wUXnUglKiqdd6P)

**Comment by saugatkandel** [comment]
Thank you!
